# syntax=docker/dockerfile:1
## Stage 1: building binaries
FROM golang:1.23.2-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build --mod=vendor ./cmd/main.go

## Stage 2: handle built binaries
FROM alpine:3.14

WORKDIR /app

COPY --from=builder /app ./
COPY --from=builder /app/main ./

RUN chmod +x main
