version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - DB_URL=${DB_URL}
      - PORT=${PORT}
    volumes:
      - .:/app
    networks:
      - friend-mgt

  build:
    build:
      context: .
      dockerfile: Dockerfile-prod
    environment:
      - DB_URL=${DB_URL}
      - PORT=${PORT}
    command: ["./main"]

  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_USER: friendmgt
      POSTGRES_PASSWORD: friendmgt
      POSTGRES_DB: friend-management
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - friend-mgt

volumes:
  pgdata:

networks:
  friend-mgt:
