services:
  app:
    image: friend-management-api:dev
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres: 
        condition: service_healthy
    environment:
      - DB_URL=${DB_URL}
      - PORT=${PORT}
    volumes:
      - .:/app
    networks:
      - friend-mgt

  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_USER: friendmgt
      POSTGRES_PASSWORD: friendmgt
      POSTGRES_DB: friend-management
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U friendmgt"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - friend-mgt

volumes:
  pgdata:

networks:
  friend-mgt:
