// Code generated by mockery v2.46.3. DO NOT EDIT.

package relationship

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

type MockController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockController) EXPECT() *MockController_Expecter {
	return &MockController_Expecter{mock: &_m.Mock}
}

// CreateFriendConn provides a mock function with given fields: ctx, inp
func (_m *MockController) CreateFriendConn(ctx context.Context, inp CreateFriendConnInp) error {
	ret := _m.Called(ctx, inp)

	if len(ret) == 0 {
		panic("no return value specified for CreateFriendConn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateFriendConnInp) error); ok {
		r0 = rf(ctx, inp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockController_CreateFriendConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFriendConn'
type MockController_CreateFriendConn_Call struct {
	*mock.Call
}

// CreateFriendConn is a helper method to define mock.On call
//   - ctx context.Context
//   - inp CreateFriendConnInp
func (_e *MockController_Expecter) CreateFriendConn(ctx interface{}, inp interface{}) *MockController_CreateFriendConn_Call {
	return &MockController_CreateFriendConn_Call{Call: _e.mock.On("CreateFriendConn", ctx, inp)}
}

func (_c *MockController_CreateFriendConn_Call) Run(run func(ctx context.Context, inp CreateFriendConnInp)) *MockController_CreateFriendConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CreateFriendConnInp))
	})
	return _c
}

func (_c *MockController_CreateFriendConn_Call) Return(_a0 error) *MockController_CreateFriendConn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockController_CreateFriendConn_Call) RunAndReturn(run func(context.Context, CreateFriendConnInp) error) *MockController_CreateFriendConn_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
