// Code generated by mockery v2.46.3. DO NOT EDIT.

package relationship

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/tanmaij/friend-management/internal/model"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, relationship
func (_m *MockRepository) Create(ctx context.Context, relationship model.Relationship) error {
	ret := _m.Called(ctx, relationship)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Relationship) error); ok {
		r0 = rf(ctx, relationship)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - relationship model.Relationship
func (_e *MockRepository_Expecter) Create(ctx interface{}, relationship interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, relationship)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, relationship model.Relationship)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Relationship))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, model.Relationship) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTwoUserIDs provides a mock function with given fields: ctx, primaryUserID, secondaryUserID
func (_m *MockRepository) ListByTwoUserIDs(ctx context.Context, primaryUserID int, secondaryUserID int) ([]model.Relationship, error) {
	ret := _m.Called(ctx, primaryUserID, secondaryUserID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTwoUserIDs")
	}

	var r0 []model.Relationship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]model.Relationship, error)); ok {
		return rf(ctx, primaryUserID, secondaryUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []model.Relationship); ok {
		r0 = rf(ctx, primaryUserID, secondaryUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Relationship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, primaryUserID, secondaryUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListByTwoUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTwoUserIDs'
type MockRepository_ListByTwoUserIDs_Call struct {
	*mock.Call
}

// ListByTwoUserIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - primaryUserID int
//   - secondaryUserID int
func (_e *MockRepository_Expecter) ListByTwoUserIDs(ctx interface{}, primaryUserID interface{}, secondaryUserID interface{}) *MockRepository_ListByTwoUserIDs_Call {
	return &MockRepository_ListByTwoUserIDs_Call{Call: _e.mock.On("ListByTwoUserIDs", ctx, primaryUserID, secondaryUserID)}
}

func (_c *MockRepository_ListByTwoUserIDs_Call) Run(run func(ctx context.Context, primaryUserID int, secondaryUserID int)) *MockRepository_ListByTwoUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_ListByTwoUserIDs_Call) Return(_a0 []model.Relationship, _a1 error) *MockRepository_ListByTwoUserIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListByTwoUserIDs_Call) RunAndReturn(run func(context.Context, int, int) ([]model.Relationship, error)) *MockRepository_ListByTwoUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
